#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_copybutton
Version  : 0.5.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/4d/a7/d9fca1553828adfb3496f6436a1c3d624d71cae76d56e569dc722f92cbca/sphinx-copybutton-0.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/4d/a7/d9fca1553828adfb3496f6436a1c3d624d71cae76d56e569dc722f92cbca/sphinx-copybutton-0.5.0.tar.gz
Summary  : Add a copy button to each of your code cells.
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_copybutton-license = %{version}-%{release}
Requires: pypi-sphinx_copybutton-python = %{version}-%{release}
Requires: pypi-sphinx_copybutton-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
# sphinx-copybutton
[![PyPI](https://img.shields.io/pypi/v/sphinx-copybutton.svg)](https://pypi.org/project/sphinx_copybutton/) | [![Conda Version](https://img.shields.io/conda/vn/conda-forge/sphinx-copybutton.svg)](https://anaconda.org/conda-forge/sphinx-copybutton) | [![Documentation](https://readthedocs.org/projects/sphinx-copybutton/badge/?version=latest)](https://sphinx-copybutton.readthedocs.io/en/latest/?badge=latest)

%package license
Summary: license components for the pypi-sphinx_copybutton package.
Group: Default

%description license
license components for the pypi-sphinx_copybutton package.


%package python
Summary: python components for the pypi-sphinx_copybutton package.
Group: Default
Requires: pypi-sphinx_copybutton-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_copybutton package.


%package python3
Summary: python3 components for the pypi-sphinx_copybutton package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_copybutton)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_copybutton package.


%prep
%setup -q -n sphinx-copybutton-0.5.0
cd %{_builddir}/sphinx-copybutton-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644181540
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_copybutton
cp %{_builddir}/sphinx-copybutton-0.5.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_copybutton/04f302f55e177936c00dce6b36ca9cf0c4e007ff
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_copybutton/04f302f55e177936c00dce6b36ca9cf0c4e007ff

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
